# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- flags:
    - -trimpath
  env:
    - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-SHA512SUMS'
  algorithm: sha512
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
signs:
  - artifacts: checksum
    signature: "${artifact}.GPG"
    args: ["--batch", "--local-user", "pancho@pancho.name", "--output", "${signature}", "--armor", "--clear-sign", "${artifact}"]
