title: Hello Go Project
#email: your-email@example.com
baseurl: "/hello-go"
url: "https://hhurtado.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: none
#plugins:
#  - jekyll-feed

excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
