name: Bump Go
on:
  push:
    branches:
      - master

jobs:
  go-bump:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2

      - name: Bump Go
        id: bump-go
        uses: BBVA/bump-go@main

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          author: GitHub <noreply@github.com>
          title: Bump Go version
          commit-message: "chore: bump Go version to ${{ steps.bump-go.outputs.go-version }}"
          branch: bump-go/patch
          delete-branch: true
