name: Bump Go
on:
  push:
    branches:
      - master

jobs:
  bump-go:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2

      - name: Bump Go
        id: bump-go
        uses: BBVA/bump-go@main

      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          title: ${{ steps.go-bump.outputs.pr-title }}
          commit-message: ${{ steps.go-bump.outputs.pr-title }}
          branch: ${{ steps.go-bump.outputs.branch-name }}
