name: Bump Go
on:
  push:
    branches:
      - master

jobs:
  go-bump:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2

      - name: Ensure we are using the latest Go release available
        id: go-bump
        uses: panchoh/go-bump@master
        with:
          go-version-path: .github/versions/go

      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          title: ${{ steps.go-bump.outputs.pr-title }}
          commit-message: ${{ steps.go-bump.outputs.pr-title }}
          branch: ${{ steps.go-bump.outputs.branch-name }}
