name: Ensure current Go compiler
on:
  schedule:
    - cron: 00 9 * * *
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  refresh-go:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Ensure we are using the latest Go release available
        id: refresh-go
        run: |
          go_version="$(
            curl --silent 'https://golang.org/dl/?mode=json' \
            | jq -r '.[0].version'                           \
            | tr -d 'go'                                     \
            | tee -a .github/versions/go
          )"
          echo "::set-output name=go-version::$go_version"
          echo "::set-output name=pr-title::update to latest Go release $go_version"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          title: ${{ steps.refresh-go.outputs.pr-title }}
          body: Auto-generated pull request created by the GitHub Action [create-pull-request](https://github.com/peter-evans/create-pull-request).
          commit-message: ${{ steps.refresh-go.outputs.pr-title }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: refresh-go/patch-${{ steps.ensure-latest-go.outputs.go-version }}
          base: master
