name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      id: setup-go
      with:
        go-version: 1.14.4

    - name: Select custom release notes
      id: release-notes
      run: |
        RELNOTES="docs/release-notes/RELEASE-${GITHUB_REF#refs/tags/}.md"
        [[ -f "$RELNOTES" ]] && echo ::set-output name=ARGS::--release-notes $RELNOTES || true

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v2
      env:
        GPG_PRIVATE_KEY: ${{ secrets.KEY }}
        # GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        # PASSPHRASE: ${{ secrets.PASSPHRASE }}

    - name: Check GO_VERSION
      run: |
        echo $GO_VERSION
      env:
        GO_VERSION: ${{ steps.setup-go.inputs.go-version }}

    - uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist ${{ steps.release-notes.outputs.ARGS }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GO_VERSION ${{ steps.setup-go.inputs.go-version }}
