name: Release

on:
  push:
    tags:
      - v*.*.*
env:
  GO_VERSION: 1.14.4

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-go@v2
      id: setup-go
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Check env
      run: |
        echo "$GO_VERSION"

    - name: Select custom release notes
      id: release-notes
      run: |
        RELNOTES="docs/release-notes/RELEASE-${GITHUB_REF#refs/tags/}.md"
        [[ -f "$RELNOTES" ]] && echo ::set-output name=ARGS::--release-notes $RELNOTES || true

    - name: Generate release signing key
      run: |
        gpg --batch --generate-key <<"EOF"
        %echo Generating a signing OpenPGP key
        %no-protection
        Key-Type: RSA
        Key-Length: 4096
        Key-Usage: sign
        Name-Real: Kapow! Release Bot
        Name-Comment: ${GITHUB_REF#refs/tags/}
        Name-Email: release-bot@kapow
        Expire-Date: 1y
        %echo done
        EOF

    - name: Import

    - uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist ${{ steps.release-notes.outputs.ARGS }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
