name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.5

    - name: Identify current version
      id: get-version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - uses: goreleaser/goreleaser-action@v1
      with:
        args: release --rm-dist --release-notes docs/release-notes/RELEASE-${{ steps.get-version.outputs.VERSION }}.md
        key: ${{ secrets.KEY }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
